doctrine:
    orm:
        mappings:
            Chat:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Chat/Domain/WriteModel'
                prefix: 'App\Chat\Domain\WriteModel'
#        controller_resolver:
#            auto_mapping: false
