framework:
    messenger:
        default_bus: chat.mercure.command.bus
        buses:
            chat.mercure.command.bus:
                # middleware:
                #     - validation
                #     - doctrine_transaction
            chat.mercure.query.bus:
                # middleware:
                #     - validation

        transports:
            chat.mercure.sync: 'sync://'
            chat.mercure.async:
                dsn: "%env(REDIS_URL)%"
                options:
                    stream: messages

        routing:
            'App\Chat\Mercure\Application\Query\GetChatMessages\GetChatMessagesQuery': chat.mercure.sync
            'App\Chat\Mercure\Application\Command\SendMessage\SendMessageCommand': chat.mercure.sync
            'App\Chat\Mercure\Domain\Event\SentMessageEvent': chat.mercure.async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more User testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
