services:
  app:
#    container_name: symfony-messenger-php
    build:
      context: ../../
      dockerfile: _docker/dev/Dockerfile
    restart: unless-stopped
    environment:
      DEFAULT_URI: "http://symfony.messenger.local"
      DATABASE_URL: "postgresql://app:app@database:5432/app?serverVersion=16&charset=utf8"
      MERCURE_URL: "http://mercure/.well-known/mercure"
      MERCURE_PUBLIC_URL: "http://symfony-messenger.localhost/.well-known/mercure"
      MERCURE_JWT_SECRET: '!ChangeThisMercureHubJWTSecretKey!'
      REDIS_URL: "redis://redis:6379"
      MESSENGER_TRANSPORT_DSN: "redis://redis:6379/messages"
    volumes:
      - ../..:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.symfony-messenger.rule=Host(`symfony-messenger.localhost`)"
      - "traefik.http.services.symfony-messenger.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    networks:
      - internal
      - web

  database:
    image: postgres:16-alpine
#    container_name: symfony-messenger-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "app", "-U", "app"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - internal
      - web

  mercure:
    image: dunglas/mercure
#    container_name: symfony-messenger-mercure
    restart: unless-stopped
    environment:
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://symfony-messenger.localhost
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    labels:
      - traefik.enable=true
      - traefik.http.routers.symfony-messenger-mercure.rule=Host(`symfony-messenger.localhost`) && PathPrefix(`/.well-known/mercure`)
      - traefik.http.services.symfony-messenger-mercure.loadbalancer.server.port=80
      - traefik.docker.network=web
    networks:
      - internal
      - web

  redis:
#    container_name: symfony-messenger-redis
    image: redis:7-alpine
    restart: unless-stopped
#    ports:
#      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

networks:
  internal:
    driver: bridge
  web:
    external: true
    name: web

volumes:
  database_data:
  redis_data:
