framework:
    messenger:
        transports:
            audit.sync: 'sync://'
            audit.async:
                dsn: "%env(REDIS_URL)%"
                options:
                    stream: messages

        routing:
            'Olek\Audit\DTO\AuditPayload': audit.sync
