framework:
    messenger:
        default_bus: mercure.chat.command.bus
        buses:
            mercure.chat.command.bus:
                # middleware:
                #     - validation
                #     - doctrine_transaction
            mercure.chat.query.bus:
                # middleware:
                #     - validation

        transports:
            sync: 'sync://'
            async:
                dsn: "%env(REDIS_URL)%"
                options:
                    stream: messages

        routing:
            'App\Mercure\Chat\Application\Query\LoadChat\LoadChatQuery': sync
            'App\Mercure\Chat\Application\Command\SendMessage\SendMessageCommand': sync
            'App\Mercure\Chat\Domain\Event\SentMessageEvent': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
