services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Chat\Application\Action\LoadChat\LoadChatAction: ~

    App\Chat\Application\Action\MessageChat\MessageChatAction: ~

    App\Chat\Domain\Service\PublisherInterface:
        class: App\Messenger\Chat\Infrastructure\Service\Publisher
